fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=500"]
        exclude: >
          (?x)^(
              package-lock\.json
          )$
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: detect-private-key

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.8
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format

  - repo: local
    hooks:
      - id: generate-openapi-schema
        name: generate OpenAPI schema
        entry: sh -c 'cd fastapi_backend && poetry run python -m commands.generate_openapi_schema'
        language: system
        pass_filenames: false
      - id: generate-frontend-client
        name: generate frontend client
        entry: sh -c 'cd nextjs-frontend && npm run generate-client'
        language: system
        # Only run frontend client generation if frontend files have changed:
        files: openapi\.json$
        pass_filenames: false