version: '3.8'
services:
  backend:
    build:
      context: ./fastapi-backend
    ports:
      - "8000:8000"
    networks:
      - my_network
    volumes:
      - ./fastapi-backend:/app
      - ./local-shared-data:/app/shared-data
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
  frontend:
    build:
      context: ./nextjs-frontend
    ports:
      - "3000:3000"
    networks:
      - my_network
    environment:
      NODE_ENV: development
    env_file:
      - ./nextjs-frontend/.env.local
    volumes:
      - ./nextjs-frontend:/app
      - nextjs-node-modules:/app/node_modules
      - nextjs-build:/app/.next
      - ./local-shared-data:/app/shared-data

volumes:
  postgres_data:
  nextjs-build:
  nextjs-node-modules:

networks:
  my_network:
    driver: bridge