version: '3.8'
services:
  backend:
    build:
      context: fastapi_backend
    environment:
      - OPENAPI_OUTPUT_FILE=./shared-data/openapi.json
    ports:
      - "8000:8000"
    networks:
      - my_network
    volumes:
      - ./fastapi_backend:/app
      - ./local-shared-data:/app/shared-data
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
  frontend:
    build:
      context: ./nextjs-frontend
    user: node
    ports:
      - "3000:3000"
    networks:
      - my_network
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_BASE_URL: http://backend:8000
      OPENAPI_OUTPUT_FILE: ./shared-data/openapi.json
    volumes:
      - ./nextjs-frontend:/app
      - nextjs-node-modules:/app/node_modules
      - ./local-shared-data:/app/shared-data

volumes:
  postgres_data:
  nextjs-node-modules:

networks:
  my_network:
    driver: bridge